# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Barton_face_display_config = debug

else ifeq ($(config),release)
  Barton_face_display_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Barton-face-display

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Barton-face-display:
ifneq (,$(Barton_face_display_config))
	@echo "==== Building Barton-face-display ($(Barton_face_display_config)) ===="
	@${MAKE} --no-print-directory -C . -f Barton-face-display.make config=$(Barton_face_display_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Barton-face-display.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Barton-face-display"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"